<div class="modal fade" id="smartcrud-delete">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Are you sure you want to delete this record?</h4>
            </div>
            <div class="modal-body">
                <p>This action is permanent and can be undone.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger btn-confirm">Delete</button>
            </div>
        </div>
    </div>
</div>
<script src="/smartcrud/js/delete.js" type="text/javascript"></script>
